// 队员信息列表

const photo = [
  [
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/1.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/2.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/3.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/4.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/5.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/6.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/7.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/8.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/9.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/10.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/11.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/12.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/13.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/14.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/15.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/16.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/17.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/18.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/19.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/20.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/21.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/22.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/23.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/24.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/25.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/26.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/27.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/28.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/29.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/30.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/31.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/32.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/33.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/34.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/35.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/36.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/37.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/38.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/39.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/40.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/41.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/42.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/43.JPG',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/game/44.JPG',
  ],  // 比赛
  [
    'http://ahu-cs-female.oss-cn-hangzhou.aliyuncs.com/image/training/1.jpg',
  ],  // 训练
  [
    'http://ahu-cs-female.oss-cn-hangzhou.aliyuncs.com/image/album/daily/1.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/album/daily/2.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/album/daily/3.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/album/daily/4.jpg',
    'http://ahu-cs-female.oss-accelerate.aliyuncs.com/image/album/daily/5.jpg',
  ],  // 日常
]
export default photo