// 队员信息列表

const photo = [
  [
    'http://codersy.cn/photo/game/1.jpg-abbr',
    'http://codersy.cn/photo/game/2.jpg-abbr',
    'http://codersy.cn/photo/game/3.jpg-abbr',
    'http://codersy.cn/photo/game/4.jpg-abbr',
    'http://codersy.cn/photo/game/5.jpg-abbr',
    'http://codersy.cn/photo/game/6.jpg-abbr',
    'http://codersy.cn/photo/game/7.jpg-abbr',
    'http://codersy.cn/photo/game/8.jpg-abbr',
    'http://codersy.cn/photo/game/9.jpg-abbr',
    'http://codersy.cn/photo/game/10.jpg-abbr',
    'http://codersy.cn/photo/game/11.jpg-abbr',
    'http://codersy.cn/photo/game/12.jpg-abbr',
    'http://codersy.cn/photo/game/13.jpg-abbr',
    'http://codersy.cn/photo/game/14.jpg-abbr',
    'http://codersy.cn/photo/game/15.jpg-abbr',
    'http://codersy.cn/photo/game/16.jpg-abbr',
    'http://codersy.cn/photo/game/17.jpg-abbr',
    'http://codersy.cn/photo/game/18.jpg-abbr',
    'http://codersy.cn/photo/game/19.jpg-abbr',
    'http://codersy.cn/photo/game/20.jpg-abbr',
    'http://codersy.cn/photo/game/21.jpg-abbr',
    'http://codersy.cn/photo/game/22.jpg-abbr',
    'http://codersy.cn/photo/game/23.jpg-abbr',
    'http://codersy.cn/photo/game/24.jpg-abbr',
    'http://codersy.cn/photo/game/25.JPG-abbr',
    'http://codersy.cn/photo/game/26.JPG-abbr',
    'http://codersy.cn/photo/game/27.JPG-abbr',
    'http://codersy.cn/photo/game/28.JPG-abbr',
    'http://codersy.cn/photo/game/29.JPG-abbr',
    'http://codersy.cn/photo/game/30.JPG-abbr',
    'http://codersy.cn/photo/game/31.jpg-abbr',
    'http://codersy.cn/photo/game/32.jpg-abbr',
    'http://codersy.cn/photo/game/33.jpg-abbr',
    'http://codersy.cn/photo/game/34.jpg-abbr',
    'http://codersy.cn/photo/game/35.jpg-abbr',
    'http://codersy.cn/photo/game/36.jpg-abbr',
    'http://codersy.cn/photo/game/37.jpg-abbr',
    'http://codersy.cn/photo/game/38.jpg-abbr',
    'http://codersy.cn/photo/game/39.jpg-abbr',
    'http://codersy.cn/photo/game/40.jpg-abbr',
    'http://codersy.cn/photo/game/41.jpg-abbr',
    'http://codersy.cn/photo/game/42.jpg-abbr',
    'http://codersy.cn/photo/game/42.jpg-abbr',
  ],  // 比赛
  [
    'http://codersy.cn/photo/train/1.jpg-abbr',
  ],  // 训练
  [
    'http://codersy.cn/photo/daily/1.jpg-abbr',
    'http://codersy.cn/photo/daily/2.jpg-abbr',
    'http://codersy.cn/photo/daily/3.jpg-abbr',
    'http://codersy.cn/photo/daily/4.jpg-abbr',
    'http://codersy.cn/photo/daily/5.jpg-abbr',
  ],  // 日常
]
export default photo